### ISSUE TITLE
Driver will fail after firmware update

### ISSUE THREAD

**Issue by impulsiva** [Magisk-Modules-Repo/ViPER4Android-FX#1]
Currently on Xiaomi Mi8 dipper, with Pixel Experience ROM. After updating the firmware, the driver will work in abnormal status and there are no way to reinstall it instead of reinstalling the module itself. Can't provide logs at the moment, I can if it's requested, only wishing the option for reinstalling the driver.

**Comment by Zackptg5** [comment]
Driver install is a mechanism of the app, not the module itself. Take it up on the xda thread and/or telegram chat for the app. There's a good chance it's already been answered there so make sure you search first. To remove currently installed driver, delete the v4a magisk mod folder and reboot
